name: Build APK from URL

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'GitHub or GitLab repo URL of the Android project'
        required: true
        default: ''
      branch:
        description: 'Branch or tag to build (optional)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get repo URL
        if: ${{ github.event.inputs.repo_url == '' }}
        run: |
          echo "❌ No repo_url provided!"
          exit 1

      - name: Fetch code from URL
        run: |
          git clone "${{ github.event.inputs.repo_url }}" project
          cd project
          if [ -n "${{ github.event.inputs.branch }}" ]; then
            git checkout "${{ github.event.inputs.branch }}"
          fi
        shell: bash

      - name: Prepare project
        run: |
          mv project/* project/.git* .
          rm -rf project

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/**/app-*.apk
